language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run lint
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
